### ISSUE TITLE
MATLAB CPU support / Python implementation? 

### ISSUE THREAD

**Issue by desaibhargav** [zikai1/GraphReg#1]
Thank you for open sourcing your work, the result are really cool. 

I wanted to know if also have the CPU version of the code? (I'm running MATLAB on macOS and it doesn't support CUDA)

Additionally, if you have a Python implementation of your work, I could run in on an environment with a GPU. 

Best, 
Bhargav

**Comment by zikai1** [comment]
> 

Hi, thanks for your interest. 

The implementation was developed on Windows 10 using CUDA, and sorry there is no Python implementation now.

 Indeed you can directly run it in Matlab on Windows without requiring additional compile or dependence.
