### ISSUE TITLE
论文中的range dataset数据集可以发布一下吗？或者描述的更加清楚一些，不太明白如何用该数据集作为原来的点云和目标点云

### ISSUE THREAD

**Issue by Zlzxzw1234** [zikai1/GraphReg#2]

**Comment by zikai1** [comment]
> _No description provided._

Hi, 

The models tested from range datasets are all named, and thus you can find and download them from the corresponding link as reported in the paper. Also, you can construct a new pair of models, by simply transforming a target model to a source one based on your own definition of the rotation and translation.
